name: "Hello world workflow"

on:
  push:
    branches:
      - main
      - master

jobs:
  First_Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello"
        run: echo "Hello World!"
      - name: "Print date"
        run: date