name: "Multi Event Pipeline / workflow"
on:
    push:
        branches:
            - main
            - test


jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on test push"
              run: echo "Running on main push"
            - name: "Print date "
              run: date