name: "Multi Event Pipeline / workflow"
on:
    push:
        branches:
            - main


jobs:
    on-push:
        run-on: ubuntu-latest
        steps:
            - name: "Running on main push"
                run: echo "Running on main push"
                run: echo "Lokesh Push this on Test branch"